// @vitest-environment node
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'
import type { Block, Diagram, Table } from '../../src/core/model'
import { parsePdf } from '../../src/core/parse/pdf'

// Fixtures are generated by scripts/make-fixtures.mjs (npm run fixtures).
const fixture = (name: string) => parsePdf(readFileSync(resolve(__dirname, '../fixtures', name)))
const summary = (blocks: Block[]) =>
  blocks.map((b) => (b.kind === 'heading' ? `h${b.level}: ${b.text}` : b.kind === 'paragraph' ? `p: ${b.text}` : b.kind))

describe('text-only.pdf', async () => {
  const doc = await fixture('text-only.pdf')

  it('yields headings and paragraphs in reading order across pages', () => {
    expect(summary(doc.blocks)).toEqual([
      'h1: Qolyozma: sinov hujjati',
      'p: Oʻzbekiston — goʻzal yurt. Bogʻlarda gʻoʻza ochildi, maʼno toʻla kun. Bu paragraf bir necha qatorga ' +
        'boʻlinadi, chunki u sahifa kengligidan uzunroq; tahlilchi qatorlarni yana bitta paragrafga yigʻishi kerak.',
      'p: Ikkinchi paragraf qisqa.',
      'h2: Kirill yozuvi',
      'p: Ўзбекистон — гўзал юрт. Қишлоқда ҳаво тоза, ғалла пишди. Ҳар бир ҳарф тўғри чиқиши керак. Ғайрат ва Қодир ҳам келди.',
      'h2: Ikkinchi bet',
      'p: The quick brown fox jumps over the lazy dog. This paragraph is on the second page.',
    ])
  })

  it('keeps Uzbek modifier letters and Cyrillic letters exactly', () => {
    const text = summary(doc.blocks).join('\n')
    for (const ch of ['ʻ', 'ʼ', 'Ў', 'ў', 'Қ', 'қ', 'Ғ', 'ғ', 'Ҳ', 'ҳ']) expect(text).toContain(ch)
    expect(text).not.toMatch(/[\u0300-\u036F]/) // composed (NFC), no stray combining marks
  })
})

describe('table.pdf', async () => {
  const doc = await fixture('table.pdf')
  const tables = doc.blocks.filter((b): b is Table => b.kind === 'table')

  it('places the tables between the surrounding text', () => {
    expect(summary(doc.blocks)).toEqual([
      'h1: Dars jadvali',
      'p: Quyidagi jadvalda haftalik darslar koʻrsatilgan.',
      'table',
      'p: Jadvaldan keyingi matn.',
      'h2: Ikkinchi jadval',
      'table',
    ])
  })

  it('reads a table drawn with stroked lines, cell by cell', () => {
    expect(tables[0]!.rows).toEqual([
      ['Kun', 'Fan', 'Xona'],
      ['Dushanba', 'Ona tili', '12'],
      ['Seshanba', 'Matematika', '7'],
      ['Chorshanba', 'Tarix', '3'],
    ])
  })

  it('reads a table whose borders are hairline filled rectangles', () => {
    expect(tables[1]!.rows).toEqual([
      ['Ism', 'Baho'],
      ['Aziza', '5'],
      ['Gʻayrat', '4'],
    ])
  })

  it('does not repeat cell text as paragraphs', () => {
    const paragraphs = doc.blocks.filter((b) => b.kind === 'paragraph').map((b) => (b as { text: string }).text)
    expect(paragraphs.join(' ')).not.toMatch(/Dushanba|Matematika|Aziza/)
  })
})

describe('diagram.pdf', async () => {
  const doc = await fixture('diagram.pdf')
  const diagrams = doc.blocks.filter((b): b is Diagram => b.kind === 'diagram')

  it('emits one diagram between the paragraphs, and no diagram for the rule under the heading', () => {
    expect(summary(doc.blocks)).toEqual([
      'h1: Ish jarayoni',
      'p: Fayl brauzerda qayta ishlanadi: avval tahlil, keyin natija.',
      'diagram',
      'p: Diagrammadan keyingi matn.',
    ])
  })

  it('keeps the boxes, arrow shafts and filled arrowheads', () => {
    const d = diagrams[0]!
    const boxes = d.shapes.filter((s) => s.closed && s.stroked && !s.filled && s.points.length === 4)
    const shafts = d.shapes.filter((s) => !s.closed && s.points.length === 2)
    const heads = d.shapes.filter((s) => s.closed && s.filled && s.points.length === 3)
    expect([boxes.length, shafts.length, heads.length]).toEqual([3, 2, 2])
    for (const s of d.shapes) {
      for (const [x, y] of s.points) {
        expect(x).toBeGreaterThanOrEqual(-0.01)
        expect(x).toBeLessThanOrEqual(d.width + 0.01)
        expect(y).toBeGreaterThanOrEqual(-0.01)
        expect(y).toBeLessThanOrEqual(d.height + 0.01)
      }
    }
  })

  it('attaches each box label to the diagram, inside its box', () => {
    const d = diagrams[0]!
    expect(d.labels.map((l) => l.text)).toEqual(['Fayl', 'Tahlil', 'Natija'])
    for (const l of d.labels) expect(l.width).toBeGreaterThan(l.fontSize) // text width, for centring redrawn labels
    const boxes = d.shapes.filter((s) => s.closed && s.stroked && !s.filled)
    d.labels.forEach((label, i) => {
      const xs = boxes[i]!.points.map((p) => p[0])
      const ys = boxes[i]!.points.map((p) => p[1])
      expect(label.x).toBeGreaterThan(Math.min(...xs))
      expect(label.x).toBeLessThan(Math.max(...xs))
      expect(label.y).toBeGreaterThan(Math.min(...ys))
      expect(label.y).toBeLessThan(Math.max(...ys))
    })
  })
})
